apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset
spec: 
  replicas: 2
  selector:
    matchLabels:
       app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: site
        image: rpcsistemas/conversao-temperatura:v1
        ports:
        - containerPort: 8080
